export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const MY_CART = "MY_CART";
export const UPDATE_CART = "UPDATE_CART";
export const MY_FAV = "MY_FAV";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
